#! /bin/sh

set -e

echo "Compiling stacktrace.cpp"
g++ -g -o stacktrace.o -c stacktrace.cpp
echo "Compiling test1.cpp"
g++ -g -o test1.o -c test1.cpp
echo "Linking test1"
g++ -o test1 test1.o stacktrace.o -lbfd -liberty
